/* GENERATED by Scripts/extract_techdata.py -- do not edit by hand.
 * source: empires2_x2_p1.dat (VER 8.9) + CivTechTrees
 * 357 techs, 39 shadow slots
 */

const int TECH_COUNT = 357;
const int SHADOW_COUNT = 39;
const int TECH_NOOP_EFFECT = 0;

void LoadTechTable() {
    addTech(    2,   454,  17, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Tarkan
    addTech(    3,   455,   1, TECH_UNIQUE                  , 2);   // Castle   Yeomen
    addTech(    4,   456,  16, TECH_UNIQUE                  , 3);   // Imperial Cotton Armors
    addTech(    5,   239,  13, TECH_UNIQUE                  , 3);   // Imperial Furor Celtica
    addTech(    6,   457,  12, TECH_UNIQUE                  , 3);   // Imperial Drill
    addTech(    7,   458,   8, TECH_UNIQUE                  , 3);   // Imperial Citadels
    addTech(    8,     8,  -1, TECH_NONE                    , 1);   // Feudal   Town Watch
    addTech(   10,   460,  10, TECH_UNIQUE                  , 3);   // Imperial Artillery
    addTech(   11,   461,   4, TECH_UNIQUE                  , 3);   // Imperial Crenellations
    addTech(   12,    12,  -1, TECH_NONE                    , 3);   // Imperial Crop Rotation
    addTech(   13,    13,  -1, TECH_NONE                    , 2);   // Castle   Heavy Plow
    addTech(   14,    14,  -1, TECH_NONE                    , 1);   // Feudal   Horse Collar
    addTech(   15,    15,  -1, TECH_NONE                    , 3);   // Imperial Guilds
    addTech(   16,   462,   3, TECH_UNIQUE                  , 2);   // Castle   Anarchy
    addTech(   17,    17,  -1, TECH_NONE                    , 3);   // Imperial Banking
    addTech(   21,   464,  17, TECH_UNIQUE                  , 3);   // Imperial Atheism
    addTech(   22,    22,  -1, TECH_NONE                    , 0);   // Dark     Loom
    addTech(   23,    23,  -1, TECH_NONE                    , 2);   // Castle   Coinage
    addTech(   24,   465,  15, TECH_UNIQUE                  , 3);   // Imperial Garland Wars
    addTech(   27,   469,  16, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Plumed Archer
    addTech(   28,    28,   9, TECH_UNIQUE                  , 2);   // Castle   Bimaristan
    addTech(   34,   155,  -1, TECH_UPGRADE                 , 2);   // Castle   Fire Ship
    addTech(   35,    -1,  -1, TECH_UPGRADE + TECH_NO_EFFECT, 3);   // Imperial Galleon
    addTech(   39,    39,  -1, TECH_NONE                    , 2);   // Castle   Husbandry
    addTech(   45,    45,  -1, TECH_NONE                    , 3);   // Imperial Exorcism
    addTech(   46,    46,  -1, TECH_NONE                    , 2);   // Castle   Devotion
    addTech(   47,    47,  -1, TECH_NONE                    , 3);   // Imperial Flaming Arrows
    addTech(   48,   482,  -1, TECH_NONE                    , 2);   // Castle   Caravan
    addTech(   49,   467,  11, TECH_UNIQUE                  , 3);   // Imperial Bogsveigar
    addTech(   50,    50,  -1, TECH_NONE                    , 2);   // Castle   Masonry
    addTech(   51,    51,  -1, TECH_NONE                    , 3);   // Imperial Architecture
    addTech(   52,   483,   6, TECH_UNIQUE                  , 3);   // Imperial Rocketry
    addTech(   54,    54,  -1, TECH_NONE                    , 2);   // Castle   Treadmill Crane
    addTech(   55,    55,  -1, TECH_NONE                    , 1);   // Feudal   Gold Mining
    addTech(   59,    59,   5, TECH_UNIQUE                  , 3);   // Imperial Kataparuto
    addTech(   60,   492,  14, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Conquistador
    addTech(   61,   493,   7, TECH_UNIQUE                  , 3);   // Imperial Logistica
    addTech(   63,    63,  -1, TECH_NONE                    , 3);   // Imperial Bastion
    addTech(   64,    64,  -1, TECH_NONE                    , 3);   // Imperial Bombard Tower
    addTech(   65,    24,  -1, TECH_NONE                    , 2);   // Castle   Gillnets
    addTech(   67,    67,  -1, TECH_NONE                    , 1);   // Feudal   Forging
    addTech(   68,    68,  -1, TECH_NONE                    , 2);   // Castle   Iron Casting
    addTech(   74,    74,  -1, TECH_NONE                    , 1);   // Feudal   Scale Mail Armor
    addTech(   75,    75,  -1, TECH_NONE                    , 3);   // Imperial Blast Furnace
    addTech(   76,    76,  -1, TECH_NONE                    , 2);   // Castle   Chain Mail Armor
    addTech(   77,    77,  -1, TECH_NONE                    , 3);   // Imperial Plate Mail Armor
    addTech(   80,    80,  -1, TECH_NONE                    , 3);   // Imperial Plate Barding Armor
    addTech(   81,    81,  -1, TECH_NONE                    , 1);   // Feudal   Scale Barding Armor
    addTech(   82,    82,  -1, TECH_NONE                    , 2);   // Castle   Chain Barding Armor
    addTech(   83,   291,   2, TECH_UNIQUE                  , 2);   // Castle   Bearded Axe
    addTech(   93,    93,  -1, TECH_NONE                    , 2);   // Castle   Target Practice
    addTech(   96,    96,  -1, TECH_UPGRADE                 , 3);   // Imperial Capped Ram
    addTech(   98,   164,  -1, TECH_UPGRADE                 , 2);   // Castle   Elite Skirmisher
    addTech(  100,   163,  -1, TECH_UPGRADE                 , 2);   // Castle   Crossbowman
    addTech(  140,   139,  -1, TECH_NONE                    , 2);   // Castle   Guard Tower
    addTech(  182,   178,  -1, TECH_NONE                    , 2);   // Castle   Gold Shaft Mining
    addTech(  194,   187,  -1, TECH_NONE                    , 2);   // Castle   Fortified Wall
    addTech(  197,   190,  -1, TECH_UPGRADE                 , 2);   // Castle   Pikeman
    addTech(  199,   192,  -1, TECH_NONE                    , 1);   // Feudal   Fletching
    addTech(  200,   193,  -1, TECH_NONE                    , 2);   // Castle   Bodkin Arrow
    addTech(  201,   194,  -1, TECH_NONE                    , 3);   // Imperial Bracer
    addTech(  202,   195,  -1, TECH_NONE                    , 1);   // Feudal   Double-Bit Axe
    addTech(  203,   196,  -1, TECH_NONE                    , 2);   // Castle   Bow Saw
    addTech(  207,   182,  -1, TECH_UPGRADE                 , 2);   // Castle   Long Swordsman
    addTech(  209,   175,  -1, TECH_UPGRADE                 , 3);   // Imperial Cavalier
    addTech(  211,   202,  -1, TECH_NONE                    , 1);   // Feudal   Padded Archer Armor
    addTech(  212,   203,  -1, TECH_NONE                    , 2);   // Castle   Leather Archer Armor
    addTech(  213,   200,  -1, TECH_NONE                    , 1);   // Feudal   Wheelbarrow
    addTech(  215,   204,  -1, TECH_NONE                    , 2);   // Castle   Squires
    addTech(  217,   206,  -1, TECH_UPGRADE                 , 2);   // Castle   Two-Handed Swordsman
    addTech(  218,   207,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Cavalry Archer
    addTech(  219,   208,  -1, TECH_NONE                    , 3);   // Imperial Ring Archer Armor
    addTech(  221,   210,  -1, TECH_NONE                    , 3);   // Imperial Two-Man Saw
    addTech(  222,   211,  -1, TECH_UPGRADE                 , 1);   // Feudal   Man-at-Arms
    addTech(  230,   220,  -1, TECH_NONE                    , 3);   // Imperial Haruspicy
    addTech(  231,   221,  -1, TECH_NONE                    , 2);   // Castle   Amulet Protection
    addTech(  233,   219,  -1, TECH_NONE                    , 3);   // Imperial Purification
    addTech(  236,   225,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Camel Rider
    addTech(  237,   226,  -1, TECH_UPGRADE                 , 3);   // Imperial Arbalester
    addTech(  239,   228,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Scorpion
    addTech(  244,   233,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Demolition Ship
    addTech(  246,   235,  -1, TECH_UPGRADE                 , 3);   // Imperial Fast Fire Ship
    addTech(  249,   238,  -1, TECH_NONE                    , 2);   // Castle   Hand Cart
    addTech(  252,   241,  -1, TECH_NONE                    , 2);   // Castle   Fervor
    addTech(  254,   245,  -1, TECH_UPGRADE                 , 2);   // Castle   Light Cavalry
    addTech(  255,   246,  -1, TECH_UPGRADE                 , 3);   // Imperial Siege Ram
    addTech(  257,   247,  -1, TECH_UPGRADE                 , 3);   // Imperial Onager
    addTech(  264,   252,  -1, TECH_UPGRADE                 , 2);   // Castle   Champion
    addTech(  265,   253,  -1, TECH_UPGRADE                 , 3);   // Imperial Paladin
    addTech(  278,   278,  -1, TECH_NONE                    , 1);   // Feudal   Stone Mining
    addTech(  279,   279,  -1, TECH_NONE                    , 2);   // Castle   Stone Shaft Mining
    addTech(  280,   280,  -1, TECH_NONE                    , 2);   // Castle   Town Patrol
    addTech(  315,   315,  -1, TECH_NONE                    , 3);   // Imperial Conscription
    addTech(  316,   316,  -1, TECH_NONE                    , 2);   // Castle   Sacrificial Dedication
    addTech(  319,   319,  -1, TECH_NONE                    , 2);   // Castle   Syncretism
    addTech(  320,   320,  -1, TECH_UPGRADE                 , 3);   // Imperial Siege Onager
    addTech(  321,   321,  -1, TECH_NONE                    , 3);   // Imperial Sappers
    addTech(  322,   236,  -1, TECH_NONE                    , 2);   // Castle   Murder Holes
    addTech(  360,   358,   1, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Longbowman
    addTech(  361,   359,   7, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Cataphract
    addTech(  362,   360,   6, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Chu Ko Nu
    addTech(  363,   361,   2, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Throwing Axeman
    addTech(  364,   362,   4, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Teutonic Knight
    addTech(  365,   363,   3, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Huskarl
    addTech(  366,   364,   5, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Samurai
    addTech(  367,   365,   8, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite War Elephant
    addTech(  368,   366,   9, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Mameluke
    addTech(  369,   367,  10, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Janissary
    addTech(  370,   368,  13, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Woad Raider
    addTech(  371,   369,  12, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Mangudai
    addTech(  372,   370,  11, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Longboat
    addTech(  373,   371,  -1, TECH_NONE                    , 3);   // Imperial Shipwright
    addTech(  374,   372,  -1, TECH_NONE                    , 2);   // Castle   Careening
    addTech(  375,   373,  -1, TECH_NONE                    , 3);   // Imperial Dry Dock
    addTech(  376,   374,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Cannon Galleon
    addTech(  377,   375,  -1, TECH_NONE                    , 3);   // Imperial Siege Engineers
    addTech(  379,   377,  -1, TECH_NONE                    , 3);   // Imperial Hoardings
    addTech(  380,   378,  -1, TECH_NONE                    , 2);   // Castle   Lighthouse
    addTech(  384,   558,  -1, TECH_UPGRADE                 , 2);   // Castle   Eagle Warrior
    addTech(  398,   397,  11, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Berserk
    addTech(  408,   420,  -1, TECH_NONE                    , 3);   // Imperial Spies/Treason
    addTech(  428,   439,  -1, TECH_UPGRADE                 , 3);   // Imperial Hussar
    addTech(  429,   189,  -1, TECH_UPGRADE                 , 3);   // Imperial Halberdier
    addTech(  432,   444,  15, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Jaguar Warrior
    addTech(  434,   445,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Eagle Warrior
    addTech(  435,   450,  -1, TECH_NONE                    , 1);   // Feudal   Bloodlines
    addTech(  436,   452,  -1, TECH_NONE                    , 3);   // Imperial Parthian Tactics
    addTech(  437,   451,  -1, TECH_NONE                    , 2);   // Castle   Thumb Ring
    addTech(  438,   494,  -1, TECH_NONE                    , 3);   // Imperial Mystery Cults
    addTech(  439,   188,  -1, TECH_NONE                    , 2);   // Castle   Hemlock
    addTech(  440,   495,  14, TECH_UNIQUE                  , 3);   // Imperial Supremacy
    addTech(  441,    41,  -1, TECH_NONE                    , 2);   // Castle   Herbal Medicine
    addTech(  445,   506,  18, TECH_UNIQUE                  , 3);   // Imperial Shinkichon
    addTech(  448,   501,  18, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Turtle Ship
    addTech(  450,   503,  18, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite War Wagon
    addTech(  454,   480,   9, TECH_UNIQUE                  , 3);   // Imperial Counterweights
    addTech(  455,   481,  23, TECH_UNIQUE                  , 2);   // Castle   Detinets
    addTech(  457,   513,   3, TECH_UNIQUE                  , 3);   // Imperial Perfusion
    addTech(  460,   514,  15, TECH_UNIQUE                  , 2);   // Castle   Atlatl
    addTech(  461,   540,   1, TECH_UNIQUE                  , 3);   // Imperial Warwolf
    addTech(  462,   516,   6, TECH_UNIQUE                  , 2);   // Castle   Great Wall
    addTech(  463,   517,  11, TECH_UNIQUE                  , 2);   // Castle   Chieftains
    addTech(  464,   518,   7, TECH_UNIQUE                  , 2);   // Castle   Greek Fire
    addTech(  468,   520,  19, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Genoese Crossbowman
    addTech(  472,   526,  22, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Magyar Huszar
    addTech(  481,   536,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Elephant Archer
    addTech(  482,   537,  13, TECH_UNIQUE                  , 2);   // Castle   Stronghold
    addTech(  483,   538,  17, TECH_UNIQUE                  , 2);   // Castle   Marauders
    addTech(  484,   539,   5, TECH_UNIQUE                  , 2);   // Castle   Yasama
    addTech(  485,   515,  16, TECH_UNIQUE                  , 2);   // Castle   Obsidian Arrows
    addTech(  486,   541,  18, TECH_UNIQUE                  , 2);   // Castle   Eupseong
    addTech(  487,   542,  12, TECH_UNIQUE                  , 2);   // Castle   Nomads
    addTech(  488,   543,   8, TECH_UNIQUE                  , 2);   // Castle   Kamandaran
    addTech(  489,   544,   4, TECH_UNIQUE                  , 2);   // Castle   Ironclad
    addTech(  491,   546,  10, TECH_UNIQUE                  , 2);   // Castle   Sipahi
    addTech(  492,   547,  14, TECH_UNIQUE                  , 2);   // Castle   Inquisition
    addTech(  493,   548,   2, TECH_UNIQUE                  , 3);   // Imperial Chivalry
    addTech(  499,   554,  19, TECH_UNIQUE                  , 2);   // Castle   Silk Road
    addTech(  504,   557,  23, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Boyar
    addTech(  506,   562,  20, TECH_UNIQUE                  , 2);   // Castle   Grand Trunk Road
    addTech(  507,   563,  20, TECH_UNIQUE                  , 3);   // Imperial Shatagni
    addTech(  509,   565,  21, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Kamayuk
    addTech(  513,   569,  23, TECH_UNIQUE                  , 3);   // Imperial Druzhina
    addTech(  514,   571,  22, TECH_UNIQUE                  , 2);   // Castle   Corvinian Army
    addTech(  515,   570,  22, TECH_UNIQUE                  , 3);   // Imperial Recurve Bow
    addTech(  516,   572,  21, TECH_UNIQUE                  , 2);   // Castle   Andean Sling
    addTech(  517,   573,  21, TECH_UNIQUE                  , 3);   // Imperial Fabric Shields
    addTech(  521,   577,  20, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Imperial Camel Rider
    addTech(  526,   581,   8, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Savar
    addTech(  563,   592,  24, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Organ Gun
    addTech(  565,   595,  27, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Camel Archer
    addTech(  567,   597,  26, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Gbeto
    addTech(  569,   599,  25, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Shotel Warrior
    addTech(  573,   602,  24, TECH_UNIQUE                  , 3);   // Imperial Arquebus
    addTech(  574,   603,  25, TECH_UNIQUE                  , 2);   // Castle   Royal Heirs
    addTech(  575,   604,  25, TECH_UNIQUE                  , 3);   // Imperial Torsion Engines
    addTech(  576,   605,  26, TECH_UNIQUE                  , 2);   // Castle   Tigui
    addTech(  577,   606,  26, TECH_UNIQUE                  , 3);   // Imperial Farimba
    addTech(  578,   607,  27, TECH_UNIQUE                  , 2);   // Castle   Kasbah
    addTech(  579,   608,  27, TECH_UNIQUE                  , 3);   // Imperial Maghrebi Camels
    addTech(  597,   623,  24, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Caravel
    addTech(  599,   625,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Genitour
    addTech(  602,   628,  -1, TECH_NONE                    , 1);   // Feudal   Arson
    addTech(  608,   633,  -1, TECH_NONE                    , 3);   // Imperial Arrowslits
    addTech(  615,   655,  28, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Ballista Elephant
    addTech(  617,   657,  29, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Karambit Warrior
    addTech(  619,   659,  30, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Arambai
    addTech(  621,   661,  31, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Rattan Archer
    addTech(  622,   662,  28, TECH_UNIQUE                  , 2);   // Castle   Tusk Swords
    addTech(  623,   663,  28, TECH_UNIQUE                  , 3);   // Imperial Double Crossbow
    addTech(  624,   664,  29, TECH_UNIQUE                  , 2);   // Castle   Thalassocracy
    addTech(  625,   665,  29, TECH_UNIQUE                  , 3);   // Imperial Forced Levy
    addTech(  626,   666,  30, TECH_UNIQUE                  , 3);   // Imperial Howdah
    addTech(  627,   667,  30, TECH_UNIQUE                  , 2);   // Castle   Manipur Cavalry
    addTech(  628,   668,  31, TECH_UNIQUE                  , 2);   // Castle   Chatras
    addTech(  629,   669,  31, TECH_UNIQUE                  , 3);   // Imperial Paper Money
    addTech(  630,   670,  -1, TECH_UPGRADE                 , 2);   // Castle   Battle Elephant
    addTech(  631,   671,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Battle Elephant
    addTech(  655,   691,  -1, TECH_UPGRADE                 , 3);   // Imperial Imperial Skirmisher
    addTech(  678,   715,  32, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Konnik
    addTech(  680,   717,  33, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Keshik
    addTech(  682,   719,  34, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Kipchak
    addTech(  684,   721,  35, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Leitis
    addTech(  685,   722,  32, TECH_UNIQUE                  , 2);   // Castle   Stirrups
    addTech(  686,   723,  32, TECH_UNIQUE                  , 3);   // Imperial Bagains
    addTech(  687,   724,  33, TECH_UNIQUE                  , 2);   // Castle   Silk Armor
    addTech(  688,   725,  33, TECH_UNIQUE                  , 3);   // Imperial Timurid Siegecraft
    addTech(  689,   726,  34, TECH_UNIQUE                  , 2);   // Castle   Steppe Husbandry
    addTech(  690,   727,  34, TECH_UNIQUE                  , 3);   // Imperial Cuman Mercenaries
    addTech(  691,   728,  35, TECH_UNIQUE                  , 2);   // Castle   Hill Forts
    addTech(  692,   729,  35, TECH_UNIQUE                  , 3);   // Imperial Tower Shields
    addTech(  715,   752,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Steppe Lancer
    addTech(  751,   787,  36, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Coustillier
    addTech(  753,   789,  37, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Serjeant
    addTech(  754,   790,  36, TECH_UNIQUE                  , 2);   // Castle   Burgundian Vineyards
    addTech(  755,   791,  36, TECH_UNIQUE                  , 3);   // Imperial Flemish Revolution
    addTech(  756,   792,  37, TECH_UNIQUE                  , 2);   // Castle   First Crusade
    addTech(  757,   793,  37, TECH_UNIQUE                  , 3);   // Imperial Hauberk
    addTech(  779,   806,  38, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Obuch
    addTech(  781,   808,  39, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Hussite Wagon
    addTech(  782,   809,  38, TECH_UNIQUE                  , 2);   // Castle   Szlachta Privileges
    addTech(  783,   810,  38, TECH_UNIQUE                  , 3);   // Imperial Lechitic Legacy
    addTech(  784,   811,  39, TECH_UNIQUE                  , 2);   // Castle   Eastern Settlement
    addTech(  785,   812,  39, TECH_UNIQUE                  , 3);   // Imperial Hussite Reforms
    addTech(  786,   813,  -1, TECH_UPGRADE                 , 3);   // Imperial Winged Hussar
    addTech(  787,   814,  39, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Houfnice
    addTech(  826,   845,  40, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Urumi Swordsman
    addTech(  828,   847,  41, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Ratha
    addTech(  830,   849,  42, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Chakram Thrower
    addTech(  831,   850,  40, TECH_UNIQUE                  , 2);   // Castle   Medical Corps
    addTech(  832,   851,  40, TECH_UNIQUE                  , 3);   // Imperial Wootz Steel
    addTech(  833,   852,  41, TECH_UNIQUE                  , 2);   // Castle   Paiks
    addTech(  834,   853,  41, TECH_UNIQUE                  , 3);   // Imperial Mahayana
    addTech(  835,   854,  42, TECH_UNIQUE                  , 2);   // Castle   Kshatriyas
    addTech(  836,   855,  42, TECH_UNIQUE                  , 3);   // Imperial Frontier Guards
    addTech(  838,   857,  -1, TECH_UPGRADE                 , 3);   // Imperial Siege Elephant
    addTech(  840,   859,  20, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Ghulam
    addTech(  843,   862,  42, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Shrivamsha Rider
    addTech(  875,   886,  -1, TECH_NONE                    , 2);   // Castle   Gambesons
    addTech(  882,   893,  43, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Centurion
    addTech(  883,   894,  43, TECH_UNIQUE                  , 2);   // Castle   Ballistas
    addTech(  884,   895,  43, TECH_UNIQUE                  , 3);   // Imperial Comitatenses
    addTech(  885,   896,  43, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Legionary
    addTech(  902,   904,  19, TECH_UNIQUE                  , 3);   // Imperial Pirotechnia
    addTech(  904,   911,  -1, TECH_UPGRADE                 , 3);   // Imperial Carrack
    addTech(  905,   912,  -1, TECH_UPGRADE                 , 2);   // Castle   Demolition Ship
    addTech(  906,   913,  -1, TECH_NONE                    , 1);   // Feudal   Fishing Lines
    addTech(  907,   909,  -1, TECH_NONE                    , 3);   // Imperial Carvel Hull
    addTech(  908,   908,  -1, TECH_NONE                    , 2);   // Castle   Clinker Construction
    addTech(  909,   915,  -1, TECH_NONE                    , 2);   // Castle   Siphons
    addTech(  910,   916,  -1, TECH_NONE                    , 3);   // Imperial Incendiaries
    addTech(  918,   930,  44, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Composite Bowman
    addTech(  920,   932,  45, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Monaspa
    addTech(  921,   933,  44, TECH_UNIQUE                  , 3);   // Imperial Fereters
    addTech(  922,   934,  44, TECH_UNIQUE                  , 2);   // Castle   Cilician Fleet
    addTech(  923,   935,  45, TECH_UNIQUE                  , 2);   // Castle   Svan Towers
    addTech(  924,   936,  45, TECH_UNIQUE                  , 3);   // Imperial Aznauri Cavalry
    addTech(  980,   980,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Rocket Cart
    addTech(  982,   982,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Fire Lancer
    addTech(  991,   991,  52, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Iron Pagoda
    addTech(  996,   996,  52, TECH_UNIQUE                  , 2);   // Castle   Fortified Bastions
    addTech(  997,   997,  52, TECH_UNIQUE                  , 3);   // Imperial Thunderclap Bombs
    addTech( 1002,  1002,  53, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Liao Dao
    addTech( 1006,  1006,  53, TECH_UNIQUE                  , 2);   // Castle   Lamellar Armor
    addTech( 1007,  1007,  53, TECH_UNIQUE                  , 3);   // Imperial Ordo Cavalry
    addTech( 1010,  1010,   6, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Dragon Ship
    addTech( 1012,  1012,  53, TECH_UNIQUE                  , 3);   // Imperial Transhumance
    addTech( 1013,  1013,  53, TECH_UNIQUE                  , 2);   // Castle   Pastoralism
    addTech( 1014,  1014,  53, TECH_UNIQUE                  , 1);   // Feudal   Domestication
    addTech( 1033,  1033,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Hei Guang Cavalry
    addTech( 1036,  1036,  51, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Tiger Cavalry
    addTech( 1061,  1061,  51, TECH_UNIQUE                  , 2);   // Castle   Tuntian
    addTech( 1062,  1062,  51, TECH_UNIQUE                  , 3);   // Imperial Ming-Kuang Armor
    addTech( 1064,  1064,  49, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite White Feather Guard
    addTech( 1069,  1069,  49, TECH_UNIQUE                  , 3);   // Imperial Bolt Magazine
    addTech( 1070,  1070,  49, TECH_UNIQUE                  , 2);   // Castle   Coiled Serpent Array
    addTech( 1074,  1074,  50, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Fire Archer
    addTech( 1080,  1080,  50, TECH_UNIQUE                  , 2);   // Castle   Red Cliff Tactics
    addTech( 1081,  1081,  50, TECH_UNIQUE                  , 3);   // Imperial Sitting Tiger
    addTech( 1110,  1110,  46, TECH_UNIQUE                  , 2);   // Castle   Sparabaras
    addTech( 1111,  1111,  46, TECH_UNIQUE                  , 2);   // Castle   Reed Arrows
    addTech( 1112,  1112,  46, TECH_UNIQUE                  , 3);   // Imperial Scythed Chariots
    addTech( 1113,  1113,  46, TECH_UNIQUE                  , 3);   // Imperial Karda
    addTech( 1115,  1116,  46, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Immortal
    addTech( 1120,  1124,  47, TECH_UNIQUE                  , 2);   // Castle   Taxiarchs
    addTech( 1121,  1123,  47, TECH_UNIQUE                  , 2);   // Castle   Iphicratean Tactics
    addTech( 1122,  1125,  47, TECH_UNIQUE                  , 3);   // Imperial Eisphora
    addTech( 1123,  1126,  47, TECH_UNIQUE                  , 3);   // Imperial Delian League
    addTech( 1125,  1128,  47, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Strategos
    addTech( 1130,  1135,  48, TECH_UNIQUE                  , 2);   // Castle   Helot Levies
    addTech( 1131,  1136,  48, TECH_UNIQUE                  , 3);   // Imperial Krypteia
    addTech( 1132,  1137,  48, TECH_UNIQUE                  , 2);   // Castle   Xyphos
    addTech( 1133,  1138,  48, TECH_UNIQUE                  , 3);   // Imperial Peloponnesian League
    addTech( 1135,  1140,  48, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Hippeus
    addTech( 1137,  1142,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Hoplite
    addTech( 1144,  1147,  -1, TECH_UPGRADE                 , 1);   // Feudal   War Lembos
    addTech( 1145,  1148,  -1, TECH_UPGRADE                 , 2);   // Castle   Heavy Lembos
    addTech( 1146,  1149,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Lembos
    addTech( 1148,  1151,  -1, TECH_UPGRADE                 , 2);   // Castle   Bireme
    addTech( 1149,  1152,  -1, TECH_UPGRADE                 , 3);   // Imperial Trireme
    addTech( 1151,  1154,  -1, TECH_UPGRADE                 , 2);   // Castle   War Galley
    addTech( 1152,  1155,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Galley
    addTech( 1154,  1157,  -1, TECH_UPGRADE                 , 2);   // Castle   Incendiary Ship
    addTech( 1155,  1158,  -1, TECH_UPGRADE                 , 3);   // Imperial Heavy Incendiary Ship
    addTech( 1156,    -1,  -1, TECH_UPGRADE + TECH_NO_EFFECT, 2);   // Castle   Jian Swordsman
    addTech( 1159,  1162,  -1, TECH_UPGRADE                 , 3);   // Imperial Onager Ship
    addTech( 1161,  1164,  -1, TECH_NONE                    , 2);   // Castle   Scoop Nets
    addTech( 1162,  1165,  -1, TECH_NONE                    , 2);   // Castle   Drums
    addTech( 1165,  1168,  -1, TECH_NONE                    , 2);   // Castle   Hypozomata
    addTech( 1167,  1170,  -1, TECH_NONE                    , 3);   // Imperial Shipwright
    addTech( 1171,  1172,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite War Chariot
    addTech( 1173,  1174,  -1, TECH_NONE                    , 3);   // Imperial Battle Drills
    addTech( 1174,  1175,  -1, TECH_UPGRADE                 , 3);   // Imperial Champion
    addTech( 1195,  1185,  46, TECH_UNIQUE                  , 1);   // Feudal   Economic Satrapy
    addTech( 1196,  1186,  46, TECH_UNIQUE                  , 1);   // Feudal   Military Satrapy
    addTech( 1197,  1187,  46, TECH_UNIQUE                  , 1);   // Feudal   Defensive Satrapy
    addTech( 1202,  1192,  47, TECH_UNIQUE                  , 0);   // Dark     Oligarchy
    addTech( 1203,  1193,  47, TECH_UNIQUE                  , 0);   // Dark     Democracy
    addTech( 1204,  1194,  47, TECH_UNIQUE                  , 0);   // Dark     Tyranny
    addTech( 1223,  1209,  48, TECH_UNIQUE                  , 2);   // Castle   Ephorate
    addTech( 1224,  1210,  48, TECH_UNIQUE                  , 2);   // Castle   Morai
    addTech( 1225,  1211,  48, TECH_UNIQUE                  , 2);   // Castle   Skeuophoroi
    addTech( 1226,  1212,  48, TECH_UNIQUE                  , 3);   // Imperial Hippagretai
    addTech( 1284,  1238,  54, TECH_UNIQUE                  , 2);   // Castle   Veteran Chiliarchs
    addTech( 1285,  1239,  54, TECH_UNIQUE                  , 2);   // Castle   Ends of the World
    addTech( 1286,  1240,  54, TECH_UNIQUE                  , 3);   // Imperial Pezhetairoi
    addTech( 1287,  1241,  54, TECH_UNIQUE                  , 3);   // Imperial Sarissophoroi
    addTech( 1289,  1243,  54, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Companion CAvalry
    addTech( 1291,  1245,  54, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Phalangite
    addTech( 1296,  1250,  55, TECH_UNIQUE                  , 2);   // Castle   Odomantian Raiders
    addTech( 1297,  1251,  55, TECH_UNIQUE                  , 2);   // Castle   Dii Plunderers
    addTech( 1298,  1252,  55, TECH_UNIQUE                  , 3);   // Imperial Bessian Metalworking
    addTech( 1299,  1253,  55, TECH_UNIQUE                  , 3);   // Imperial Peltasts
    addTech( 1301,  1255,  55, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Rhomphaia Warrior
    addTech( 1307,  1261,  56, TECH_UNIQUE                  , 2);   // Castle   Vadhavadha
    addTech( 1308,  1262,  56, TECH_UNIQUE                  , 2);   // Castle   Leaf-Headed Shafts
    addTech( 1309,  1263,  56, TECH_UNIQUE                  , 3);   // Imperial Vedic Teachings
    addTech( 1310,  1264,  56, TECH_UNIQUE                  , 3);   // Imperial Skandhavaras
    addTech( 1326,  1269,  56, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Pattiyodha Longbowman
    addTech( 1328,  1271,  56, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Sannahya
    addTech( 1350,  1350,  -1, TECH_UPGRADE                 , 0);   // Dark     Champi Scout
    addTech( 1351,  1351,  -1, TECH_UPGRADE                 , 2);   // Castle   Champi Warrior
    addTech( 1352,  1352,  -1, TECH_UPGRADE                 , 3);   // Imperial Elite Champi Warrior
    addTech( 1364,  1364,  57, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Guecha Warrior
    addTech( 1365,  1365,  57, TECH_UNIQUE                  , 2);   // Castle   Herbalism
    addTech( 1366,  1366,  57, TECH_UNIQUE                  , 3);   // Imperial Fabric Shields
    addTech( 1376,  1376,  58, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Kona
    addTech( 1378,  1378,  58, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Bolas Rider
    addTech( 1379,  1379,  58, TECH_UNIQUE                  , 2);   // Castle   Malon
    addTech( 1380,  1380,  58, TECH_UNIQUE                  , 3);   // Imperial Butalmapu
    addTech( 1389,  1389,  59, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Blackwood Archer
    addTech( 1391,  1391,  59, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Ibirapema Warrior
    addTech( 1392,  1392,  59, TECH_UNIQUE                  , 2);   // Castle   Caciques
    addTech( 1393,  1393,  59, TECH_UNIQUE                  , 3);   // Imperial Curare
    addTech( 1401,  1401,  57, TECH_UPGRADE + TECH_UNIQUE   , 3);   // Imperial Elite Temple Guard
    addTech( 1402,  1402,  -1, TECH_UPGRADE                 , 1);   // Feudal   Champi Runner
    addTech( 1404,  1404,  24, TECH_UNIQUE                  , 2);   // Castle   Circumnavigation
}

void LoadShadows() {
    addShadow(1181);
    addShadow(1182);
    addShadow(1183);
    addShadow(1184);
    addShadow(1185);
    addShadow(1186);
    addShadow(1187);
    addShadow(1188);
    addShadow(1189);
    addShadow(1240);
    addShadow(1241);
    addShadow(1242);
    addShadow(1243);
    addShadow(1244);
    addShadow(1245);
    addShadow(1246);
    addShadow(1247);
    addShadow(1248);
    addShadow(1249);
    addShadow(1340);
    addShadow(1341);
    addShadow(1342);
    addShadow(1343);
    addShadow(1344);
    addShadow(1345);
    addShadow(1346);
    addShadow(1347);
    addShadow(1348);
    addShadow(1349);
    addShadow(1500);
    addShadow(1501);
    addShadow(1502);
    addShadow(1503);
    addShadow(1504);
    addShadow(1505);
    addShadow(1506);
    addShadow(1507);
    addShadow(1508);
    addShadow(1509);
}

int vanillaAgeFor(int scenarioId = -1) {
    switch(scenarioId) {
        case 101: { return (0); }
        case 102: { return (2); }
        case 103: { return (2); }
        case 104: { return (2); }
        case 105: { return (2); }
        case 106: { return (3); }
        case 201: { return (2); }
        case 202: { return (1); }
        case 203: { return (1); }
        case 204: { return (2); }
        case 205: { return (3); }
        case 206: { return (2); }
    }
    return (0);
}
